name: Build and test

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Build
      run: go build -v ./...

    - name: Run vet
      run: go vet ./...
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Run coverage
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
